// import IdsTag from "./components/IdsTag.vue";
// import IdsModal from "./components/IdsModal.vue";
// import IdsButton from "./components/IdsButton.vue";
// import IdsAvatar from "./components/IdsAvatar.vue";
// import IdsDivider from "./components/IdsIconButton.vue";
// import IdsIconButton from "./components/IdsIconButton.vue";
// import IdsActionItem from "./components/IdsActionItem.vue";
// import IdsActionMenu from "./components/IdsActionMenu.vue";

// export { IdsTag };
// export { IdsModal };
// export { IdsAvatar };
// export { IdsButton };
// export { IdsDivider };
// export { IdsIconButton };
// export { IdsActionItem };
// export { IdsActionMenu };


export { default as IdsVue } from "./core/config/IdsVue.ts";
export { default as IdsTag } from "./components/tag/IdsTag.vue";
export { default as IdsDialog } from "./components/IdsDialog.vue";
export { default as IdsButton } from "./components/button/IdsButton.vue";
export { default as IdsAvatar } from "./components/IdsAvatar.vue";
export { default as IdsDivider } from "./components/divider/IdsDivider.vue";
export { default as IdsAccordion } from "./components/IdsAccordion.vue";
export { default as IdsIconButton } from "./components/icon-button/IdsIconButton.vue";
export { default as IdsActionItem } from "./components/action-item/IdsActionItem.vue";
export { default as IdsActionPanel } from "./components/action-panel/IdsActionPanel.vue";
export { default as IdsActionMenu } from "./components/IdsActionMenu.vue";
export { default as IdsCheckbox } from "./components/checkbox/IdsCheckbox.vue";
export { default as IdsHintMessage } from "./components/message/IdsHintMessage.vue";
export { default as IdsErrorMessage } from "./components/message/IdsErrorMessage.vue";
export { default as IdsSuccessMessage } from "./components/message/IdsSuccessMessage.vue";
export { default as IdsPaginator } from "./components/paginator/IdsPaginator.vue";
export { default as IdsIcon } from "./components/icon/IdsIcon.vue";
export { default as IdsSegmentedControl } from "./components/segmented-control/IdsSegmentedControl.vue";
export { default as IdsSegmentedControlToggle } from "./components/segmented-control/IdsSegmentedControlToggle.vue";
export { default as IdsSegmentedControlItem } from "./components/segmented-control/IdsSegmentedControlItem.vue";
export { default as IdsSegmentedControlToggleItem } from "./components/segmented-control/IdsSegmentedControlToggleItem.vue";
export { default as IdsRadioGroup } from "./components/radio/IdsRadioGroup.vue";
export { default as IdsRadioItem } from "./components/radio/IdsRadioItem.vue";